name: Setup Databricks CLI

description: |
  Download the latest Databricks CLI snapshot build and add it to $PATH.

inputs:
  snapshot:
    description: 'Install a snapshot build (set to "true" to enable).'
    required: false

  token:
    description: '(snapshot build only) A GitHub PAT to access the CLI repository.'
    required: false

  branch:
    description: '(snapshot build only) The branch to download the snapshot build for.'
    required: false

runs:
  using: "composite"
  steps:
    - name: Download snapshot build
      if: ${{ inputs.snapshot == 'true' }}
      shell: bash
      run: bash $GITHUB_ACTION_PATH/setup_snapshot.sh
      env:
        GH_REPO: databricks/cli
        GH_TOKEN: ${{ inputs.token }}
        BRANCH: ${{ inputs.branch }}

    - name: Download release build
      if: ${{ inputs.snapshot != 'true' }}
      shell: bash
      run: bash $GITHUB_ACTION_PATH/setup_release.sh
      env:
        VERSION: 0.100.0

    - name: Get Databricks CLI version
      shell: bash
      run: databricks version --detail | jq .
