name: Setup Bricks CLI

description: |
  Download the latest Bricks CLI snapshot build and add it to $PATH.

inputs:
  snapshot:
    description: 'Install a snapshot build (set to "true" to enable).'
    required: false

  token:
    description: '(snapshot build only) A GitHub PAT to access the Bricks repository.'
    required: false

  branch:
    description: '(snapshot build only) The branch to download the snapshot build for.'
    required: false

runs:
  using: "composite"
  steps:
    - name: Download snapshot build
      if: ${{ inputs.snapshot == 'true' }}
      shell: bash
      run: bash $GITHUB_ACTION_PATH/setup_snapshot.sh
      env:
        GH_REPO: databricks/bricks
        GH_TOKEN: ${{ inputs.token }}
        BRICKS_BRANCH: ${{ inputs.branch }}

    - name: Download release build
      if: ${{ inputs.snapshot != 'true' }}
      shell: bash
      run: bash $GITHUB_ACTION_PATH/setup_release.sh
      env:
        VERSION: 0.0.31

    - name: Get Bricks version
      shell: bash
      run: bricks version --detail | jq .
