name: Setup Bricks CLI

description: |
  Download the latest Bricks CLI snapshot build and add it to $PATH.

inputs:
  token:
    description: 'A GitHub PAT'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download snapshot build
      shell: bash
      run: bash ${{ github.action_path }}/download.sh
      env:
        GH_REPO: databricks/bricks
        GH_TOKEN: ${{ inputs.token }}

    - name: Fix permissions
      shell: bash
      run: chmod +x .bin/bricks_*/bricks*

    - name: Add to $PATH
      shell: bash
      run: |
        dir="$PWD/.bin/bricks"

        # Append correct os name.
        case $RUNNER_OS in
        Linux)
          dir="${dir}_linux"
          ;;
        Windows)
          dir="${dir}_windows"
          ;;
        macOS)
          dir="${dir}_darwin"
          ;;
        esac

        # Append correct arch name.
        case $RUNNER_ARCH in
        X86)
          dir="${dir}_386"
          ;;
        X64)
          dir="${dir}_amd64_v1"
          ;;
        ARM)
          dir="${dir}_arm_6"
          ;;
        ARM64)
          dir="${dir}_arm64"
          ;;
        esac

        if [ ! -d "$dir" ]; then
          echo "Directory does not exist: $dir"
          exit 1
        fi

        if [ "$RUNNER_OS" == "Windows" ]; then
          cd $dir
          mv ./bricks.exe ./bricks
        fi

        echo "$dir" >> $GITHUB_PATH
